name = "DiscontinuousGherkins"
uuid = "045df00d-45f8-45a7-ae4b-f424bb4a0af0"
authors = ["ali.hh.ramadhan@gmail.com <ali.hh.ramadhan@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
